name: Manual Update Server

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server to set as active'
        required: true
        type: choice
        options:
          - 'zimbor.go.ro'
          - 'zimbor.go.ro:8985'
          - 'srvalx.duckdns.org:8983'
        default: 'zimbor.go.ro'

jobs:
  manual-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update Configuration File Manually
      run: |
        CONFIG_FILE="v3/config.php"
        BACKUP_FILE="$CONFIG_FILE.bak"
        manual_server="${{ github.event.inputs.server }}"

        # Backup the original config file
        cp $CONFIG_FILE $BACKUP_FILE

        # Ignore the backup file
        echo "$BACKUP_FILE" >> .gitignore
        git add .gitignore

        # Escape single quotes and other special characters in the server name
        escaped_manual_server=$(echo "$manual_server" | sed "s/[']/\\\\'/g")

        # Comment out all existing server lines
        sed -i -e 's/^\s*\$server = /\/\/\$server = /' $CONFIG_FILE

        # Uncomment the line for the manual server
        sed -i "s/\/\/\$server = '$manual_server';/\$server = '$manual_server';/" $CONFIG_FILE

        # Create a new branch for the PR
        git checkout -b update-server-${{ github.sha }}

        # Commit the changes
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add $CONFIG_FILE
        git commit -m "Manually updated server to $manual_server"

    - name: Push changes and create PR
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin update-server-${{ github.sha }}
        gh pr create --title "Update server to $manual_server" --body "This PR updates the server configuration." --head update-server-${{ github.sha }} --base master

    - name: Auto-merge PR
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=$(gh pr list --head update-server-${{ github.sha }} --json number --jq '.[0].number')
        gh pr merge $PR_NUMBER --squash --delete-branch
