name: Run PHPUnit Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: phpunit
        coverage: xdebug # Explicitly installs Xdebug 3.x

    - name: Update dependencies
      run: composer update --prefer-dist --no-progress

    - name: Create coverage directory
      run: mkdir -p coverage-report

    - name: Run PHPUnit tests and generate report
      run: |
        vendor/bin/phpunit \
          --configuration phpunit.xml \
          --coverage-html ${{ github.workspace }}/coverage-report

    - name: Debug directory structure
      run: |
        pwd
        ls -la
        ls -la coverage-report/

    - name: Archive coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ github.workspace }}/coverage-report/
