name: Run PHPUnit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: phpunit, composer
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check for Xdebug or PCOV
      run: php -m | grep -E 'xdebug|pcov'

    - name: Display PHP configuration
      run: php -i | grep 'xdebug\|pcov'

    - name: Run PHPUnit tests and generate coverage report
      run: |
        vendor/bin/phpunit --configuration phpunit.xml --coverage-html coverage-report || { echo 'PHPUnit failed'; exit 1; }
        if [ -d "coverage-report" ]; then
          echo "Coverage report directory exists:"
          ls -la coverage-report
        else
          echo "Coverage report directory does not exist"
          exit 1
        fi

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage-report/
